const ALBUMS = [
  {
    "rank": 1,
    "year": 2022,
    "artist": "The Wonder Years",
    "album": "The Hum Goes On Forever",
    "score": 100.0,
    "personalScore": 9.8,
    "trackCount": 12,
    "genre1": "Emo Rock",
    "genre2": "Pop Punk",
    "duration": "0:44:37",
    "favoriteSong": "Low Tide",
    "releaseDate": "Sep 23, 2022",
    "releaseDateISO": "2022-09-23"
  },
  {
    "rank": 2,
    "year": 2021,
    "artist": "Every Time I Die",
    "album": "Radical",
    "score": 99.4,
    "personalScore": 9.6,
    "trackCount": 16,
    "genre1": "Hardcore Punk",
    "genre2": "Metalcore",
    "duration": "0:51:17",
    "favoriteSong": "All This And War",
    "releaseDate": "Oct 22, 2021",
    "releaseDateISO": "2021-10-22"
  },
  {
    "rank": 3,
    "year": 2022,
    "artist": "The Beths",
    "album": "Expert In A Dying Field",
    "score": 97.3,
    "personalScore": 9.5,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Power Pop",
    "duration": "0:44:59",
    "favoriteSong": "Silence Is Golden",
    "releaseDate": "Sep 16, 2022",
    "releaseDateISO": "2022-09-16"
  },
  {
    "rank": 4,
    "year": 2023,
    "artist": "Fireworks",
    "album": "Higher Lonely Power",
    "score": 96.6,
    "personalScore": 9.5,
    "trackCount": 12,
    "genre1": "Emo Pop Punk",
    "genre2": "Midwest Emo",
    "duration": "0:43:55",
    "favoriteSong": "How Did It Use to Be So Easy?",
    "releaseDate": "Jan 1, 2023",
    "releaseDateISO": "2023-01-01"
  },
  {
    "rank": 5,
    "year": 2021,
    "artist": "Julien Baker",
    "album": "Little Oblivions",
    "score": 96.5,
    "personalScore": 9.8,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Singer-Songwriter",
    "duration": "0:42:44",
    "favoriteSong": "Ringside",
    "releaseDate": "Feb 26, 2021",
    "releaseDateISO": "2021-02-26"
  },
  {
    "rank": 6,
    "year": 2020,
    "artist": "The Front Bottoms",
    "album": "In Sickness & In Flames",
    "score": 95.6,
    "personalScore": 9.4,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Folk Punk",
    "duration": "0:52:39",
    "favoriteSong": "bus beat",
    "releaseDate": "Aug 21, 2020",
    "releaseDateISO": "2020-08-21"
  },
  {
    "rank": 7,
    "year": 2022,
    "artist": "Mom Jeans.",
    "album": "Sweet Tooth",
    "score": 95.4,
    "personalScore": 9.3,
    "trackCount": 13,
    "genre1": "Emo Pop",
    "genre2": "Indie Rock",
    "duration": "0:37:10",
    "favoriteSong": "Luv L8r",
    "releaseDate": "Feb 25, 2022",
    "releaseDateISO": "2022-02-25"
  },
  {
    "rank": 8,
    "year": 2025,
    "artist": "Portugal. The Man",
    "album": "SHISH",
    "score": 95.0,
    "personalScore": 9.8,
    "trackCount": 10,
    "genre1": "Psychedelic Pop",
    "genre2": "Indie Rock",
    "duration": "0:41:49",
    "favoriteSong": "Tanana",
    "releaseDate": "Nov 7, 2025",
    "releaseDateISO": "2025-11-07"
  },
  {
    "rank": 9,
    "year": 2024,
    "artist": "Royel Otis",
    "album": "PRATTS & PAIN",
    "score": 94.9,
    "personalScore": 9.5,
    "trackCount": 17,
    "genre1": "Indie Rock",
    "genre2": "Dream Pop",
    "duration": "0:40:46",
    "favoriteSong": "Foam",
    "releaseDate": "Feb 16, 2024",
    "releaseDateISO": "2024-02-16"
  },
  {
    "rank": 10,
    "year": 2025,
    "artist": "Hayley Williams",
    "album": "Ego Death At A Bachelorette Party",
    "score": 94.6,
    "personalScore": 9.5,
    "trackCount": 18,
    "genre1": "Alt Pop",
    "genre2": "Indie Rock",
    "duration": "1:00:06",
    "favoriteSong": "Love Me Different",
    "releaseDate": "Nov 7, 2025",
    "releaseDateISO": "2025-11-07"
  },
  {
    "rank": 11,
    "year": 2023,
    "artist": "blink-182",
    "album": "ONE MORE TIME",
    "score": 94.2,
    "personalScore": 9.2,
    "trackCount": 19,
    "genre1": "Pop Punk",
    "genre2": "Alternative Rock",
    "duration": "0:50:03",
    "favoriteSong": "Turpentine",
    "releaseDate": "Oct 27, 2023",
    "releaseDateISO": "2023-10-27"
  },
  {
    "rank": 12,
    "year": 2020,
    "artist": "Hot Mulligan",
    "album": "you'll be fine",
    "score": 93.9,
    "personalScore": 9.8,
    "trackCount": 11,
    "genre1": "Emo",
    "genre2": "Pop-Punk",
    "duration": "0:31:17",
    "favoriteSong": "SPS",
    "releaseDate": "Mar 6, 2020",
    "releaseDateISO": "2020-03-06"
  },
  {
    "rank": 13,
    "year": 2020,
    "artist": "Spanish Love Songs",
    "album": "Brave Faces Everyone",
    "score": 93.9,
    "personalScore": 9.6,
    "trackCount": 10,
    "genre1": "Emo Punk",
    "genre2": "Indie Rock",
    "duration": "0:40:28",
    "favoriteSong": "Optimism (As a Radical Life Choice)",
    "releaseDate": "Feb 7, 2020",
    "releaseDateISO": "2020-02-07"
  },
  {
    "rank": 14,
    "year": 2022,
    "artist": "The Regrettes",
    "album": "Further Joy",
    "score": 93.2,
    "personalScore": 9.1,
    "trackCount": 13,
    "genre1": "Pop Rock",
    "genre2": "Indie Pop",
    "duration": "0:43:41",
    "favoriteSong": "La Di Da",
    "releaseDate": "Apr 8, 2022",
    "releaseDateISO": "2022-04-08"
  },
  {
    "rank": 15,
    "year": 2021,
    "artist": "Turnstile",
    "album": "GLOW ON",
    "score": 93.1,
    "personalScore": 9.7,
    "trackCount": 15,
    "genre1": "Hardcore Punk",
    "genre2": "Alternative Rock",
    "duration": "0:34:57",
    "favoriteSong": "MYSTERY",
    "releaseDate": "Aug 27, 2021",
    "releaseDateISO": "2021-08-27"
  },
  {
    "rank": 16,
    "year": 2023,
    "artist": "Hot Mulligan",
    "album": "Why Would I Watch",
    "score": 92.9,
    "personalScore": 9.7,
    "trackCount": 12,
    "genre1": "Emo Pop Punk",
    "genre2": "Midwest Emo",
    "duration": "0:37:24",
    "favoriteSong": "Gans Media Retro Games",
    "releaseDate": "May 12, 2023",
    "releaseDateISO": "2023-05-12"
  },
  {
    "rank": 17,
    "year": 2023,
    "artist": "Trophy Eyes",
    "album": "Suicide and Sunshine",
    "score": 92.4,
    "personalScore": 9.3,
    "trackCount": 14,
    "genre1": "Alternative Rock",
    "genre2": "Emo Punk",
    "duration": "0:40:16",
    "favoriteSong": "Take Me Back To Eden",
    "releaseDate": "Jun 23, 2023",
    "releaseDateISO": "2023-06-23"
  },
  {
    "rank": 18,
    "year": 2024,
    "artist": "JPEGMAFIA",
    "album": "I LAY DOWN MY LIFE FOR YOU",
    "score": 92.3,
    "personalScore": 9.3,
    "trackCount": 14,
    "genre1": "Experimental Hip-Hop",
    "genre2": "Noise Rap",
    "duration": "0:41:24",
    "favoriteSong": "either on or off the drugs",
    "releaseDate": "Aug 1, 2024",
    "releaseDateISO": "2024-08-01"
  },
  {
    "rank": 19,
    "year": 2025,
    "artist": "Jesse Welles",
    "album": "With The Devil",
    "score": 92.3,
    "personalScore": 9.6,
    "trackCount": 11,
    "genre1": "Americana Rock",
    "genre2": "Folk Rock",
    "duration": "0:50:40",
    "favoriteSong": "America, Girl",
    "releaseDate": "Aug 22, 2025",
    "releaseDateISO": "2025-08-22"
  },
  {
    "rank": 20,
    "year": 2023,
    "artist": "Post Malone",
    "album": "AUSTIN",
    "score": 92.0,
    "personalScore": 9.0,
    "trackCount": 18,
    "genre1": "Pop Rock",
    "genre2": "Country Pop",
    "duration": "0:51:47",
    "favoriteSong": "Mourning",
    "releaseDate": "Jul 28, 2023",
    "releaseDateISO": "2023-07-28"
  },
  {
    "rank": 21,
    "year": 2021,
    "artist": "Manchster Orchestra",
    "album": "The Million Masks of God",
    "score": 91.9,
    "personalScore": 9.4,
    "trackCount": 11,
    "genre1": "Indie Rock",
    "genre2": "Alt Rock",
    "duration": "0:45:58",
    "favoriteSong": "Keel Timing",
    "releaseDate": "Apr 30, 2021",
    "releaseDateISO": "2021-04-30"
  },
  {
    "rank": 22,
    "year": 2021,
    "artist": "Twenty One Pilots",
    "album": "Scaled And Icy",
    "score": 91.7,
    "personalScore": 9.0,
    "trackCount": 11,
    "genre1": "Alternative Pop",
    "genre2": "Electropop",
    "duration": "0:37:42",
    "favoriteSong": "Formidable",
    "releaseDate": "May 21, 2021",
    "releaseDateISO": "2021-05-21"
  },
  {
    "rank": 23,
    "year": 2021,
    "artist": "Japanese Breakfast",
    "album": "Jubilee",
    "score": 91.5,
    "personalScore": 9.5,
    "trackCount": 10,
    "genre1": "Indie Pop",
    "genre2": "Dream Pop",
    "duration": "0:37:03",
    "favoriteSong": "Posing For Cars",
    "releaseDate": "Jun 4, 2021",
    "releaseDateISO": "2021-06-04"
  },
  {
    "rank": 24,
    "year": 2025,
    "artist": "Petey USA",
    "album": "The Yips",
    "score": 91.4,
    "personalScore": 9.4,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Heartland Alt",
    "duration": "0:46:14",
    "favoriteSong": "Model Train Town",
    "releaseDate": "Jul 11, 2025",
    "releaseDateISO": "2025-07-11"
  },
  {
    "rank": 25,
    "year": 2020,
    "artist": "The Menzingers",
    "album": "From Exile",
    "score": 91.3,
    "personalScore": 9.0,
    "trackCount": 12,
    "genre1": "Alternative Rock",
    "genre2": "Americana",
    "duration": "0:44:57",
    "favoriteSong": "I Can't Stop Drinking",
    "releaseDate": "Sep 25, 2020",
    "releaseDateISO": "2020-09-25"
  },
  {
    "rank": 26,
    "year": 2024,
    "artist": "MGMT",
    "album": "Loss Of Life",
    "score": 91.2,
    "personalScore": 9.1,
    "trackCount": 10,
    "genre1": "Psychedelic Pop",
    "genre2": "Synthpop",
    "duration": "0:45:13",
    "favoriteSong": "Mother Nature",
    "releaseDate": "Feb 23, 2024",
    "releaseDateISO": "2024-02-23"
  },
  {
    "rank": 27,
    "year": 2021,
    "artist": "You, Me, And Everyone We Know",
    "album": "Something Heavy",
    "score": 90.7,
    "personalScore": 9.2,
    "trackCount": 10,
    "genre1": "Emo",
    "genre2": "Indie Rock",
    "duration": "0:34:55",
    "favoriteSong": "Ram Dass Dick Pics",
    "releaseDate": "Sep 17, 2021",
    "releaseDateISO": "2021-09-17"
  },
  {
    "rank": 28,
    "year": 2021,
    "artist": "Origami Angel",
    "album": "GAMI GANG",
    "score": 90.5,
    "personalScore": 9.1,
    "trackCount": 20,
    "genre1": "Emo",
    "genre2": "Pop Punk",
    "duration": "0:51:21",
    "favoriteSong": "Isopropyl Alchemy",
    "releaseDate": "Apr 30, 2021",
    "releaseDateISO": "2021-04-30"
  },
  {
    "rank": 29,
    "year": 2023,
    "artist": "Sleep Token",
    "album": "Take Me Back To Eden",
    "score": 90.1,
    "personalScore": 8.8,
    "trackCount": 12,
    "genre1": "Progressive Metal",
    "genre2": "Art Rock",
    "duration": "1:03:00",
    "favoriteSong": "DYWTYLM",
    "releaseDate": "May 19, 2023",
    "releaseDateISO": "2023-05-19"
  },
  {
    "rank": 30,
    "year": 2022,
    "artist": "Soul Glo",
    "album": "Diaspora Problems",
    "score": 89.8,
    "personalScore": 8.7,
    "trackCount": 12,
    "genre1": "Hardcore Punk",
    "genre2": "Rapcore",
    "duration": "0:39:14",
    "favoriteSong": "Gold Chain Punk (whogonbeatmyass?)",
    "releaseDate": "Mar 25, 2022",
    "releaseDateISO": "2022-03-25"
  },
  {
    "rank": 31,
    "year": 2025,
    "artist": "Beach Bunny",
    "album": "Tunnel Vision",
    "score": 88.9,
    "personalScore": 9.3,
    "trackCount": 10,
    "genre1": "Indie Pop",
    "genre2": "Power Pop",
    "duration": "0:29:49",
    "favoriteSong": "Just Around The Corner",
    "releaseDate": "Apr 25, 2025",
    "releaseDateISO": "2025-04-25"
  },
  {
    "rank": 32,
    "year": 2023,
    "artist": "Gorillaz",
    "album": "Cracker Island",
    "score": 88.8,
    "personalScore": 8.8,
    "trackCount": 10,
    "genre1": "Alt Pop",
    "genre2": "Funk Rock",
    "duration": "0:37:29",
    "favoriteSong": "Skinny Ape",
    "releaseDate": "Feb 24, 2023",
    "releaseDateISO": "2023-02-24"
  },
  {
    "rank": 33,
    "year": 2022,
    "artist": "Beach Bunny",
    "album": "Emotional Creature",
    "score": 87.9,
    "personalScore": 9.0,
    "trackCount": 12,
    "genre1": "Indie Pop",
    "genre2": "Power Pop",
    "duration": "0:35:59",
    "favoriteSong": "Weeds",
    "releaseDate": "Jul 22, 2022",
    "releaseDateISO": "2022-07-22"
  },
  {
    "rank": 34,
    "year": 2024,
    "artist": "The Decemberists",
    "album": "As It Ever Was, So It Will Be Again",
    "score": 87.8,
    "personalScore": 8.5,
    "trackCount": 14,
    "genre1": "Indie Folk",
    "genre2": "Baroque Rock",
    "duration": "1:07:00",
    "favoriteSong": "All I Want Is You",
    "releaseDate": "Jun 14, 2024",
    "releaseDateISO": "2024-06-14"
  },
  {
    "rank": 35,
    "year": 2025,
    "artist": "Michigander",
    "album": "Michigander",
    "score": 87.7,
    "personalScore": 8.5,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Alt Pop",
    "duration": "0:41:35",
    "favoriteSong": "I'll Be Okay",
    "releaseDate": "Feb 7, 2025",
    "releaseDateISO": "2025-02-07"
  },
  {
    "rank": 36,
    "year": 2022,
    "artist": "Spanish Love Songs",
    "album": "Brave Faces Etc.",
    "score": 87.7,
    "personalScore": 8.6,
    "trackCount": 10,
    "genre1": "Emo Rock",
    "genre2": "Indie Rock",
    "duration": "0:43:49",
    "favoriteSong": "",
    "releaseDate": "Apr 15, 2022",
    "releaseDateISO": "2022-04-15"
  },
  {
    "rank": 37,
    "year": 2025,
    "artist": "Turnstile",
    "album": "NEVER ENOUGH",
    "score": 87.7,
    "personalScore": 9.2,
    "trackCount": 14,
    "genre1": "Hardcore Punk",
    "genre2": "Alternative",
    "duration": "0:45:14",
    "favoriteSong": "SUNSHOWER",
    "releaseDate": "Jun 6, 2025",
    "releaseDateISO": "2025-06-06"
  },
  {
    "rank": 38,
    "year": 2025,
    "artist": "The Beths",
    "album": "Straight Line Was A Lie",
    "score": 87.5,
    "personalScore": 9.7,
    "trackCount": 10,
    "genre1": "Indie Rock",
    "genre2": "Power Pop",
    "duration": "0:43:42",
    "favoriteSong": "Mother, Pray for Me",
    "releaseDate": "Aug 29, 2025",
    "releaseDateISO": "2025-08-29"
  },
  {
    "rank": 39,
    "year": 2023,
    "artist": "That Mexican OT",
    "album": "Lonestar Luchador",
    "score": 87.5,
    "personalScore": 9.1,
    "trackCount": 13,
    "genre1": "Southern Rap",
    "genre2": "Trap",
    "duration": "0:38:16",
    "favoriteSong": "Johnny Dang",
    "releaseDate": "Jul 28, 2023",
    "releaseDateISO": "2023-07-28"
  },
  {
    "rank": 40,
    "year": 2023,
    "artist": "The Front Bottoms",
    "album": "You Are Who You Hang Out With",
    "score": 87.4,
    "personalScore": 8.6,
    "trackCount": 10,
    "genre1": "Indie Rock",
    "genre2": "Folk Punk",
    "duration": "0:35:58",
    "favoriteSong": "Outlook",
    "releaseDate": "Aug 4, 2023",
    "releaseDateISO": "2023-08-04"
  },
  {
    "rank": 41,
    "year": 2022,
    "artist": "Ethel Cain",
    "album": "Preacher's Daughter",
    "score": 87.2,
    "personalScore": 8.9,
    "trackCount": 13,
    "genre1": "Gothic Pop",
    "genre2": "Slowcore",
    "duration": "1:15:00",
    "favoriteSong": "Family Tree",
    "releaseDate": "May 12, 2022",
    "releaseDateISO": "2022-05-12"
  },
  {
    "rank": 42,
    "year": 2025,
    "artist": "Tyler Childers",
    "album": "Snipe Hunter",
    "score": 87.0,
    "personalScore": 8.7,
    "trackCount": 13,
    "genre1": "Country",
    "genre2": "Americana",
    "duration": "0:53:59",
    "favoriteSong": "Bitin' List",
    "releaseDate": "Jul 25, 2025",
    "releaseDateISO": "2025-07-25"
  },
  {
    "rank": 43,
    "year": 2020,
    "artist": "Pinegrove",
    "album": "Marigold",
    "score": 86.8,
    "personalScore": 8.9,
    "trackCount": 11,
    "genre1": "Indie Rock",
    "genre2": "Alt Country",
    "duration": "0:37:34",
    "favoriteSong": "Endless",
    "releaseDate": "Jan 17, 2020",
    "releaseDateISO": "2020-01-17"
  },
  {
    "rank": 44,
    "year": 2021,
    "artist": "This Wild Life",
    "album": "Ever Blossom",
    "score": 86.8,
    "personalScore": 8.5,
    "trackCount": 10,
    "genre1": "Acoustic",
    "genre2": "Pop Rock",
    "duration": "0:35:18",
    "favoriteSong": "You Swore Your Love Would Burn",
    "releaseDate": "Oct 15, 2021",
    "releaseDateISO": "2021-10-15"
  },
  {
    "rank": 45,
    "year": 2022,
    "artist": "Just Friends",
    "album": "Hella",
    "score": 86.8,
    "personalScore": 8.2,
    "trackCount": 12,
    "genre1": "Funk Rock",
    "genre2": "Emo Pop",
    "duration": "0:38:19",
    "favoriteSong": "Stupid",
    "releaseDate": "Mar 4, 2022",
    "releaseDateISO": "2022-03-04"
  },
  {
    "rank": 46,
    "year": 2024,
    "artist": "Kendrick Lamar",
    "album": "GNX",
    "score": 86.1,
    "personalScore": 8.9,
    "trackCount": 12,
    "genre1": "Hip-Hop",
    "genre2": "Conscious Rap",
    "duration": "0:44:20",
    "favoriteSong": "squabble up",
    "releaseDate": "Nov 22, 2024",
    "releaseDateISO": "2024-11-22"
  },
  {
    "rank": 47,
    "year": 2024,
    "artist": "Aaron West",
    "album": "In Lieu of Flowers",
    "score": 84.3,
    "personalScore": 8.4,
    "trackCount": 11,
    "genre1": "Folk Punk",
    "genre2": "Indie Rock",
    "duration": "0:43:26",
    "favoriteSong": "Spitting In The Wind",
    "releaseDate": "Apr 12, 2024",
    "releaseDateISO": "2024-04-12"
  },
  {
    "rank": 48,
    "year": 2020,
    "artist": "Phoebe Bridgers",
    "album": "Punisher",
    "score": 83.7,
    "personalScore": 8.8,
    "trackCount": 10,
    "genre1": "Indie Folk",
    "genre2": "Singer-Songwriter",
    "duration": "0:40:42",
    "favoriteSong": "Graceland Too",
    "releaseDate": "Jun 18, 2020",
    "releaseDateISO": "2020-06-18"
  },
  {
    "rank": 49,
    "year": 2021,
    "artist": "The Killers",
    "album": "Pressure Machine",
    "score": 83.7,
    "personalScore": 8.2,
    "trackCount": 11,
    "genre1": "Heartland Rock",
    "genre2": "Americana",
    "duration": "0:51:22",
    "favoriteSong": "Desperate Things",
    "releaseDate": "Aug 13, 2021",
    "releaseDateISO": "2021-08-13"
  },
  {
    "rank": 50,
    "year": 2025,
    "artist": "Anxious",
    "album": "Bambi",
    "score": 83.7,
    "personalScore": 8.9,
    "trackCount": 11,
    "genre1": "Emo",
    "genre2": "Melodic Hardcore",
    "duration": "0:40:11",
    "favoriteSong": "Head & Spine",
    "releaseDate": "Feb 21, 2025",
    "releaseDateISO": "2025-02-21"
  },
  {
    "rank": 51,
    "year": 2025,
    "artist": "Jesse Welles",
    "album": "Devil's Den",
    "score": 83.4,
    "personalScore": 9.0,
    "trackCount": 11,
    "genre1": "Folk Rock",
    "genre2": "Americana",
    "duration": "0:49:35",
    "favoriteSong": "This Age",
    "releaseDate": "Aug 22, 2025",
    "releaseDateISO": "2025-08-22"
  },
  {
    "rank": 52,
    "year": 2025,
    "artist": "Tiny Voices",
    "album": "Reasons I Won't Change",
    "score": 83.1,
    "personalScore": 9.1,
    "trackCount": 11,
    "genre1": "Emo",
    "genre2": "Pop Punk",
    "duration": "0:35:05",
    "favoriteSong": "Yesterday",
    "releaseDate": "Mar 14, 2025",
    "releaseDateISO": "2025-03-14"
  },
  {
    "rank": 53,
    "year": 2021,
    "artist": "Citizen",
    "album": "Life in Your Glass World",
    "score": 82.5,
    "personalScore": 8.9,
    "trackCount": 11,
    "genre1": "Indie Rock",
    "genre2": "Post-Punk Revival",
    "duration": "0:37:40",
    "favoriteSong": "I Want To Kill You",
    "releaseDate": "Mar 26, 2021",
    "releaseDateISO": "2021-03-26"
  },
  {
    "rank": 54,
    "year": 2020,
    "artist": "Run The Jewels",
    "album": "RTJ4",
    "score": 82.0,
    "personalScore": 8.0,
    "trackCount": 11,
    "genre1": "Hip-Hop",
    "genre2": "Political Rap",
    "duration": "0:39:03",
    "favoriteSong": "JU$T",
    "releaseDate": "Jun 3, 2020",
    "releaseDateISO": "2020-06-03"
  },
  {
    "rank": 55,
    "year": 2025,
    "artist": "Clipse",
    "album": "Let God Sort Em Out",
    "score": 81.8,
    "personalScore": 8.4,
    "trackCount": 13,
    "genre1": "Hip-Hop",
    "genre2": "Coke Rap",
    "duration": "0:40:52",
    "favoriteSong": "F.I.C.O.",
    "releaseDate": "Jul 11, 2025",
    "releaseDateISO": "2025-07-11"
  },
  {
    "rank": 56,
    "year": 2022,
    "artist": "Anxious",
    "album": "Little Green House",
    "score": 81.7,
    "personalScore": 8.3,
    "trackCount": 10,
    "genre1": "Emo Punk",
    "genre2": "Post-Hardcore",
    "duration": "0:32:09",
    "favoriteSong": "Speechless",
    "releaseDate": "Jan 21, 2022",
    "releaseDateISO": "2022-01-21"
  },
  {
    "rank": 57,
    "year": 2022,
    "artist": "The 1975",
    "album": "Being Funny In A Foreign Language",
    "score": 81.6,
    "personalScore": 8.1,
    "trackCount": 11,
    "genre1": "Indie Pop",
    "genre2": "Synthpop",
    "duration": "0:39:47",
    "favoriteSong": "",
    "releaseDate": "Oct 14, 2022",
    "releaseDateISO": "2022-10-14"
  },
  {
    "rank": 58,
    "year": 2025,
    "artist": "Nolan Taylor",
    "album": "Nolan Taylor",
    "score": 81.2,
    "personalScore": 8.3,
    "trackCount": 16,
    "genre1": "Folk",
    "genre2": "Singer-Songwriter",
    "duration": "0:56:39",
    "favoriteSong": "I Belong In Your Arms",
    "releaseDate": "Jan 10, 2025",
    "releaseDateISO": "2025-01-10"
  },
  {
    "rank": 59,
    "year": 2021,
    "artist": "Sir Sly",
    "album": "The Rise & Fall of Loverboy",
    "score": 81.0,
    "personalScore": 8.7,
    "trackCount": 14,
    "genre1": "Indie Pop",
    "genre2": "Synth Rock",
    "duration": "0:48:42",
    "favoriteSong": "Loverboy",
    "releaseDate": "Apr 3, 2021",
    "releaseDateISO": "2021-04-03"
  },
  {
    "rank": 60,
    "year": 2024,
    "artist": "Microwave",
    "album": "Let's Start Degeneracy",
    "score": 80.9,
    "personalScore": 8.7,
    "trackCount": 10,
    "genre1": "Alt Rock",
    "genre2": "Emo",
    "duration": "0:30:27",
    "favoriteSong": "Circling The Drain",
    "releaseDate": "Apr 26, 2024",
    "releaseDateISO": "2024-04-26"
  },
  {
    "rank": 61,
    "year": 2022,
    "artist": "The Dangerous Summer",
    "album": "Coming Home",
    "score": 80.8,
    "personalScore": 8.4,
    "trackCount": 11,
    "genre1": "Alternative Rock",
    "genre2": "Emo Rock",
    "duration": "0:37:35",
    "favoriteSong": "Someday",
    "releaseDate": "Aug 26, 2022",
    "releaseDateISO": "2022-08-26"
  },
  {
    "rank": 62,
    "year": 2023,
    "artist": "Movements",
    "album": "RUCKUS!",
    "score": 80.7,
    "personalScore": 7.7,
    "trackCount": 10,
    "genre1": "Post-Hardcore",
    "genre2": "Emo Rock",
    "duration": "0:36:15",
    "favoriteSong": "Fail You",
    "releaseDate": "Aug 18, 2023",
    "releaseDateISO": "2023-08-18"
  },
  {
    "rank": 63,
    "year": 2022,
    "artist": "The Mars Volta",
    "album": "The Mars Volta",
    "score": 80.5,
    "personalScore": 8.5,
    "trackCount": 14,
    "genre1": "Progressive Rock",
    "genre2": "Latin Fusion",
    "duration": "0:44:52",
    "favoriteSong": "Cerulea",
    "releaseDate": "Sep 16, 2022",
    "releaseDateISO": "2022-09-16"
  },
  {
    "rank": 64,
    "year": 2020,
    "artist": "Dance Gavin Dance",
    "album": "Afterburner",
    "score": 80.4,
    "personalScore": 6.7,
    "trackCount": 13,
    "genre1": "Post-Hardcore",
    "genre2": "Experimental Rock",
    "duration": "0:48:29",
    "favoriteSong": "Three Wishes",
    "releaseDate": "Apr 24, 2020",
    "releaseDateISO": "2020-04-24"
  },
  {
    "rank": 65,
    "year": 2020,
    "artist": "Hayley Williams",
    "album": "Petals For Armor",
    "score": 80.4,
    "personalScore": 7.7,
    "trackCount": 15,
    "genre1": "Art Pop",
    "genre2": "Indie Rock",
    "duration": "0:55:51",
    "favoriteSong": "Dead Horse",
    "releaseDate": "May 8, 2020",
    "releaseDateISO": "2020-05-08"
  },
  {
    "rank": 66,
    "year": 2020,
    "artist": "Soccer Mommy",
    "album": "color theory",
    "score": 80.2,
    "personalScore": 7.9,
    "trackCount": 10,
    "genre1": "Indie Pop",
    "genre2": "Dream Pop",
    "duration": "0:44:13",
    "favoriteSong": "yellow is the color of her eyes",
    "releaseDate": "Feb 28, 2020",
    "releaseDateISO": "2020-02-28"
  },
  {
    "rank": 67,
    "year": 2023,
    "artist": "Ben Howard",
    "album": "Is It?",
    "score": 80.2,
    "personalScore": 8.4,
    "trackCount": 10,
    "genre1": "Indie Folk",
    "genre2": "Ambient Pop",
    "duration": "0:42:16",
    "favoriteSong": "Walking Backwards",
    "releaseDate": "Jun 16, 2023",
    "releaseDateISO": "2023-06-16"
  },
  {
    "rank": 68,
    "year": 2024,
    "artist": "Young Jesus",
    "album": "The Fool",
    "score": 80.1,
    "personalScore": 8.2,
    "trackCount": 11,
    "genre1": "Experimental Folk",
    "genre2": "Art Rock",
    "duration": "0:46:02",
    "favoriteSong": "MOTY",
    "releaseDate": "May 24, 2024",
    "releaseDateISO": "2024-05-24"
  },
  {
    "rank": 69,
    "year": 2024,
    "artist": "Dehd",
    "album": "Poetry",
    "score": 80.0,
    "personalScore": 8.3,
    "trackCount": 14,
    "genre1": "Indie Pop",
    "genre2": "Garage Rock",
    "duration": "0:41:01",
    "favoriteSong": "Knife",
    "releaseDate": "May 10, 2024",
    "releaseDateISO": "2024-05-10"
  },
  {
    "rank": 70,
    "year": 2025,
    "artist": "Jesse Welles",
    "album": "Pilgrim",
    "score": 79.7,
    "personalScore": 8.6,
    "trackCount": 11,
    "genre1": "Americana",
    "genre2": "Folk Rock",
    "duration": "0:38:12",
    "favoriteSong": "Change Is In The Air",
    "releaseDate": "Jul 4, 2025",
    "releaseDateISO": "2025-07-04"
  },
  {
    "rank": 71,
    "year": 2024,
    "artist": "That Mexican OT",
    "album": "Texas Technician",
    "score": 79.5,
    "personalScore": 7.4,
    "trackCount": 15,
    "genre1": "Trap",
    "genre2": "Southern Hip-Hop",
    "duration": "0:40:34",
    "favoriteSong": "Twisting Fingers",
    "releaseDate": "Mar 1, 2024",
    "releaseDateISO": "2024-03-01"
  },
  {
    "rank": 72,
    "year": 2020,
    "artist": "The Beths",
    "album": "Jump Rope Gazers",
    "score": 79.4,
    "personalScore": 8.7,
    "trackCount": 10,
    "genre1": "Indie Pop",
    "genre2": "Power Pop",
    "duration": "0:38:50",
    "favoriteSong": "Jump Rope Gazers",
    "releaseDate": "Jul 10, 2020",
    "releaseDateISO": "2020-07-10"
  },
  {
    "rank": 73,
    "year": 2023,
    "artist": "Emarosa",
    "album": "Sting",
    "score": 79.1,
    "personalScore": 8.1,
    "trackCount": 10,
    "genre1": "Synthpop",
    "genre2": "Alternative Pop",
    "duration": "0:34:03",
    "favoriteSong": "Attention",
    "releaseDate": "Jun 27, 2023",
    "releaseDateISO": "2023-06-27"
  },
  {
    "rank": 74,
    "year": 2023,
    "artist": "Spanish Love Songs",
    "album": "No Joy",
    "score": 78.8,
    "personalScore": 8.0,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Emo",
    "duration": "0:45:11",
    "favoriteSong": "Haunted",
    "releaseDate": "Aug 25, 2023",
    "releaseDateISO": "2023-08-25"
  },
  {
    "rank": 75,
    "year": 2025,
    "artist": "My Morning Jacket",
    "album": "is",
    "score": 78.7,
    "personalScore": 7.8,
    "trackCount": 10,
    "genre1": "Psychedelic Rock",
    "genre2": "Indie",
    "duration": "0:39:01",
    "favoriteSong": "Half a Lifetime",
    "releaseDate": "Mar 21, 2025",
    "releaseDateISO": "2025-03-21"
  },
  {
    "rank": 76,
    "year": 2025,
    "artist": "Motion City Soundtrack",
    "album": "The Same Old Wasted Wonderful World",
    "score": 77.5,
    "personalScore": 8.5,
    "trackCount": 11,
    "genre1": "Emo Pop",
    "genre2": "Power Pop",
    "duration": "0:35:31",
    "favoriteSong": "Some Wear a Dark Heart",
    "releaseDate": "Sep 19, 2025",
    "releaseDateISO": "2025-09-19"
  },
  {
    "rank": 77,
    "year": 2021,
    "artist": "The Dirty Nil",
    "album": "Fuck Art",
    "score": 77.3,
    "personalScore": 8.6,
    "trackCount": 11,
    "genre1": "Garage Rock",
    "genre2": "Punk Rock",
    "duration": "0:35:10",
    "favoriteSong": "Doom Boy",
    "releaseDate": "Jan 1, 2021",
    "releaseDateISO": "2021-01-01"
  },
  {
    "rank": 78,
    "year": 2022,
    "artist": "CLIFFDIVER",
    "album": "Exercise Your Demons",
    "score": 77.1,
    "personalScore": 7.5,
    "trackCount": 9,
    "genre1": "Emo Pop",
    "genre2": "Alt Rock",
    "duration": "0:29:18",
    "favoriteSong": "",
    "releaseDate": "May 6, 2022",
    "releaseDateISO": "2022-05-06"
  },
  {
    "rank": 79,
    "year": 2021,
    "artist": "Angels & Airwaves",
    "album": "Lifeforms",
    "score": 77.1,
    "personalScore": 7.5,
    "trackCount": 10,
    "genre1": "Alt Rock",
    "genre2": "Space Rock",
    "duration": "0:37:52",
    "favoriteSong": "Euphoria",
    "releaseDate": "Sep 24, 2021",
    "releaseDateISO": "2021-09-24"
  },
  {
    "rank": 80,
    "year": 2023,
    "artist": "Tyler Childers",
    "album": "Rustin' In The Rain",
    "score": 77.0,
    "personalScore": 7.6,
    "trackCount": 8,
    "genre1": "Americana",
    "genre2": "Country Folk",
    "duration": "0:28:01",
    "favoriteSong": "In Your Love",
    "releaseDate": "Sep 8, 2023",
    "releaseDateISO": "2023-09-08"
  },
  {
    "rank": 81,
    "year": 2024,
    "artist": "Post Malone",
    "album": "F-1 Trillion: Long Bed",
    "score": 76.7,
    "personalScore": 7.8,
    "trackCount": 27,
    "genre1": "Pop Rock",
    "genre2": "Country Pop",
    "duration": "1:27:00",
    "favoriteSong": "What Don't Belong To Me",
    "releaseDate": "Aug 16, 2024",
    "releaseDateISO": "2024-08-16"
  },
  {
    "rank": 82,
    "year": 2022,
    "artist": "Future Teens",
    "album": "Self Help",
    "score": 76.7,
    "personalScore": 8.0,
    "trackCount": 10,
    "genre1": "Indie Rock",
    "genre2": "Emo Pop",
    "duration": "0:32:39",
    "favoriteSong": "Stress Dream",
    "releaseDate": "Sep 23, 2022",
    "releaseDateISO": "2022-09-23"
  },
  {
    "rank": 83,
    "year": 2021,
    "artist": "Driveways",
    "album": "Skeptic",
    "score": 76.2,
    "personalScore": 8.4,
    "trackCount": 7,
    "genre1": "Emo Rock",
    "genre2": "Pop Punk",
    "duration": "0:24:23",
    "favoriteSong": "78",
    "releaseDate": "Oct 29, 2021",
    "releaseDateISO": "2021-10-29"
  },
  {
    "rank": 84,
    "year": 2021,
    "artist": "Couplet",
    "album": "LP1",
    "score": 76.1,
    "personalScore": 7.7,
    "trackCount": 11,
    "genre1": "Indie Pop",
    "genre2": "Synthpop",
    "duration": "0:32:57",
    "favoriteSong": "Old Elba",
    "releaseDate": "Oct 1, 2021",
    "releaseDateISO": "2021-10-01"
  },
  {
    "rank": 85,
    "year": 2024,
    "artist": "Kings of Leon",
    "album": "Can We Please Have Fun",
    "score": 76.1,
    "personalScore": 8.1,
    "trackCount": 12,
    "genre1": "Alt Rock",
    "genre2": "Heartland Rock",
    "duration": "0:44:55",
    "favoriteSong": "Mustang",
    "releaseDate": "May 10, 2024",
    "releaseDateISO": "2024-05-10"
  },
  {
    "rank": 86,
    "year": 2023,
    "artist": "Sincere Engineer",
    "album": "Cheap Grills",
    "score": 76.1,
    "personalScore": 7.1,
    "trackCount": 12,
    "genre1": "Pop Punk",
    "genre2": "Emo Rock",
    "duration": "0:40:03",
    "favoriteSong": "Old Coat Pocket",
    "releaseDate": "Sep 22, 2023",
    "releaseDateISO": "2023-09-22"
  },
  {
    "rank": 87,
    "year": 2024,
    "artist": "Blink-182",
    "album": "ONE MORE TIME...PART 2",
    "score": 75.9,
    "personalScore": 6.5,
    "trackCount": 8,
    "genre1": "Pop Punk",
    "genre2": "Emo Pop",
    "duration": "1:14:00",
    "favoriteSong": "ALL IN MY HEAD",
    "releaseDate": "Sep 6, 2024",
    "releaseDateISO": "2024-09-06"
  },
  {
    "rank": 88,
    "year": 2022,
    "artist": "Have Mercy",
    "album": "I'm Gonna Be Okay",
    "score": 75.7,
    "personalScore": 7.7,
    "trackCount": 7,
    "genre1": "Emo Rock",
    "genre2": "Alternative",
    "duration": "0:25:17",
    "favoriteSong": "",
    "releaseDate": "Aug 26, 2022",
    "releaseDateISO": "2022-08-26"
  },
  {
    "rank": 89,
    "year": 2020,
    "artist": "The Wonder Years",
    "album": "Burst & Decay (Volume II)",
    "score": 75.6,
    "personalScore": 7.5,
    "trackCount": 8,
    "genre1": "Acoustic Rock",
    "genre2": "Emo",
    "duration": "0:30:49",
    "favoriteSong": "Washington Square Park",
    "releaseDate": "Feb 14, 2020",
    "releaseDateISO": "2020-02-14"
  },
  {
    "rank": 90,
    "year": 2021,
    "artist": "Hot Mulligan",
    "album": "I Won't Reach Out To You / Acoustic",
    "score": 75.6,
    "personalScore": 8.8,
    "trackCount": 9,
    "genre1": "Emo",
    "genre2": "Acoustic Rock",
    "duration": "0:11:57",
    "favoriteSong": "Please Don't Cry, You Have Swag",
    "releaseDate": "May 28, 2021",
    "releaseDateISO": "2021-05-28"
  },
  {
    "rank": 91,
    "year": 2020,
    "artist": "Eastwood",
    "album": "It Never Gets Easy",
    "score": 75.0,
    "personalScore": 8.6,
    "trackCount": 11,
    "genre1": "Emo",
    "genre2": "Indie Rock",
    "duration": "0:42:41",
    "favoriteSong": "False Start",
    "releaseDate": "Sep 18, 2020",
    "releaseDateISO": "2020-09-18"
  },
  {
    "rank": 92,
    "year": 2022,
    "artist": "Camp Trash",
    "album": "The Long Way, The Slow Way",
    "score": 74.3,
    "personalScore": 7.4,
    "trackCount": 12,
    "genre1": "Emo Rock",
    "genre2": "Indie Punk",
    "duration": "0:39:47",
    "favoriteSong": "",
    "releaseDate": "Jul 1, 2022",
    "releaseDateISO": "2022-07-01"
  },
  {
    "rank": 93,
    "year": 2024,
    "artist": "Joyner Lucas",
    "album": "Not Now I'm Busy",
    "score": 74.3,
    "personalScore": 6.9,
    "trackCount": 17,
    "genre1": "Hip-Hop",
    "genre2": "Trap",
    "duration": "1:02:00",
    "favoriteSong": "I'm Ill",
    "releaseDate": "Mar 22, 2024",
    "releaseDateISO": "2024-03-22"
  },
  {
    "rank": 94,
    "year": 2025,
    "artist": "The Starting Line",
    "album": "Eternal Youth",
    "score": 73.9,
    "personalScore": 8.2,
    "trackCount": 11,
    "genre1": "Indie",
    "genre2": "Pop Punk",
    "duration": "0:35:50",
    "favoriteSong": "Circulate",
    "releaseDate": "Sep 26, 2025",
    "releaseDateISO": "2025-09-26"
  },
  {
    "rank": 95,
    "year": 2021,
    "artist": "Remember Sports",
    "album": "Like a Stone",
    "score": 73.8,
    "personalScore": 7.9,
    "trackCount": 12,
    "genre1": "Indie Punk",
    "genre2": "Garage Rock",
    "duration": "0:37:54",
    "favoriteSong": "Out Loud",
    "releaseDate": "Apr 23, 2021",
    "releaseDateISO": "2021-04-23"
  },
  {
    "rank": 96,
    "year": 2023,
    "artist": "Petey",
    "album": "USA",
    "score": 73.6,
    "personalScore": 7.9,
    "trackCount": 11,
    "genre1": "Indie Rock",
    "genre2": "Alt Pop",
    "duration": "0:42:44",
    "favoriteSong": "The Freedom to Fuck Off",
    "releaseDate": "Sep 22, 2023",
    "releaseDateISO": "2023-09-22"
  },
  {
    "rank": 97,
    "year": 2022,
    "artist": "Dehd",
    "album": "Blue Skies",
    "score": 73.5,
    "personalScore": 7.6,
    "trackCount": 13,
    "genre1": "Indie Rock",
    "genre2": "Dream Pop",
    "duration": "0:32:34",
    "favoriteSong": "",
    "releaseDate": "May 27, 2022",
    "releaseDateISO": "2022-05-27"
  },
  {
    "rank": 98,
    "year": 2021,
    "artist": "Tigers Jaw",
    "album": "I Won't Care How You Remember Me",
    "score": 73.4,
    "personalScore": 6.8,
    "trackCount": 11,
    "genre1": "Indie Rock",
    "genre2": "Emo",
    "duration": "0:34:15",
    "favoriteSong": "I Won't Care How You Remember Me",
    "releaseDate": "Mar 5, 2021",
    "releaseDateISO": "2021-03-05"
  },
  {
    "rank": 99,
    "year": 2025,
    "artist": "PUP",
    "album": "Who Will Look After The Dogs?",
    "score": 73.3,
    "personalScore": 7.7,
    "trackCount": 12,
    "genre1": "Punk Rock",
    "genre2": "Emo",
    "duration": "0:35:50",
    "favoriteSong": "Concrete",
    "releaseDate": "May 2, 2025",
    "releaseDateISO": "2025-05-02"
  },
  {
    "rank": 100,
    "year": 2023,
    "artist": "Metric",
    "album": "Formentera II",
    "score": 73.2,
    "personalScore": 7.2,
    "trackCount": 9,
    "genre1": "Indie Pop",
    "genre2": "Synthpop",
    "duration": "0:40:02",
    "favoriteSong": "Go Ahead and Cry",
    "releaseDate": "Oct 13, 2023",
    "releaseDateISO": "2023-10-13"
  },
  {
    "rank": 101,
    "year": 2023,
    "artist": "Oragami Angel",
    "album": "The Brightest Days",
    "score": 72.8,
    "personalScore": 7.8,
    "trackCount": 8,
    "genre1": "Emo Pop",
    "genre2": "Indie Punk",
    "duration": "0:22:09",
    "favoriteSong": "Second Best Friend",
    "releaseDate": "Jun 16, 2023",
    "releaseDateISO": "2023-06-16"
  },
  {
    "rank": 102,
    "year": 2022,
    "artist": "PUP",
    "album": "THE UNRAVELING OF PUPTHEBAND",
    "score": 72.1,
    "personalScore": 7.3,
    "trackCount": 10,
    "genre1": "Punk Rock",
    "genre2": "Emo",
    "duration": "0:35:50",
    "favoriteSong": "",
    "releaseDate": "Apr 1, 2022",
    "releaseDateISO": "2022-04-01"
  },
  {
    "rank": 103,
    "year": 2022,
    "artist": "Oso Oso",
    "album": "Sore Thumb",
    "score": 71.8,
    "personalScore": 7.9,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Emo",
    "duration": "0:37:01",
    "favoriteSong": "",
    "releaseDate": "Mar 18, 2022",
    "releaseDateISO": "2022-03-18"
  },
  {
    "rank": 104,
    "year": 2024,
    "artist": "Macseal",
    "album": "Permanent Repeat",
    "score": 71.7,
    "personalScore": 7.6,
    "trackCount": 11,
    "genre1": "Emo",
    "genre2": "Math Rock",
    "duration": "0:32:20",
    "favoriteSong": "Easily Undone",
    "releaseDate": "Jul 12, 2024",
    "releaseDateISO": "2024-07-12"
  },
  {
    "rank": 105,
    "year": 2023,
    "artist": "Zach Bryan",
    "album": "Zach Bryan",
    "score": 71.4,
    "personalScore": 7.3,
    "trackCount": 16,
    "genre1": "Country",
    "genre2": "Americana",
    "duration": "0:54:23",
    "favoriteSong": "Overtime",
    "releaseDate": "Aug 25, 2023",
    "releaseDateISO": "2023-08-25"
  },
  {
    "rank": 106,
    "year": 2021,
    "artist": "Real Friends",
    "album": "Torn in Two",
    "score": 71.3,
    "personalScore": 6.5,
    "trackCount": 10,
    "genre1": "Pop Punk",
    "genre2": "Emo Rock",
    "duration": "0:30:22",
    "favoriteSong": "Storyteller",
    "releaseDate": "Sep 17, 2021",
    "releaseDateISO": "2021-09-17"
  },
  {
    "rank": 107,
    "year": 2023,
    "artist": "The Ongoing Concept",
    "album": "Again",
    "score": 71.2,
    "personalScore": 7.5,
    "trackCount": 9,
    "genre1": "Post-Hardcore",
    "genre2": "Experimental Rock",
    "duration": "0:35:16",
    "favoriteSong": "Feel Again",
    "releaseDate": "Mar 31, 2023",
    "releaseDateISO": "2023-03-31"
  },
  {
    "rank": 109,
    "year": 2023,
    "artist": "The Japanese House",
    "album": "In the End it Always Does",
    "score": 70.6,
    "personalScore": 7.4,
    "trackCount": 12,
    "genre1": "Dream Pop",
    "genre2": "Indie Synthpop",
    "duration": "0:45:05",
    "favoriteSong": "You Always Get What You Want",
    "releaseDate": "Jun 30, 2023",
    "releaseDateISO": "2023-06-30"
  },
  {
    "rank": 110,
    "year": 2024,
    "artist": "Balance & Composure",
    "album": "with you in spirit",
    "score": 70.5,
    "personalScore": 7.1,
    "trackCount": 10,
    "genre1": "Emo Rock",
    "genre2": "Shoegaze",
    "duration": "0:37:50",
    "favoriteSong": "any means",
    "releaseDate": "Oct 4, 2024",
    "releaseDateISO": "2024-10-04"
  },
  {
    "rank": 111,
    "year": 2022,
    "artist": "Beabadoobee",
    "album": "Beatopia",
    "score": 70.1,
    "personalScore": 7.0,
    "trackCount": 14,
    "genre1": "Indie Pop",
    "genre2": "Shoegaze",
    "duration": "0:45:44",
    "favoriteSong": "",
    "releaseDate": "Jul 15, 2022",
    "releaseDateISO": "2022-07-15"
  },
  {
    "rank": 112,
    "year": 2023,
    "artist": "FRND CRCL",
    "album": "Suburban Dictionary",
    "score": 69.9,
    "personalScore": 6.8,
    "trackCount": 14,
    "genre1": "Pop Punk",
    "genre2": "Easycore",
    "duration": "0:36:45",
    "favoriteSong": "Golden",
    "releaseDate": "Jun 30, 2023",
    "releaseDateISO": "2023-06-30"
  },
  {
    "rank": 113,
    "year": 2022,
    "artist": "Young Jesus",
    "album": "Shepherd Head",
    "score": 69.9,
    "personalScore": 7.8,
    "trackCount": 8,
    "genre1": "Experimental Folk",
    "genre2": "Ambient Rock",
    "duration": "0:27:56",
    "favoriteSong": "",
    "releaseDate": "Sep 16, 2022",
    "releaseDateISO": "2022-09-16"
  },
  {
    "rank": 114,
    "year": 2024,
    "artist": "J. Cole",
    "album": "Might Delete Later",
    "score": 69.7,
    "personalScore": 6.8,
    "trackCount": 13,
    "genre1": "Hip-Hop",
    "genre2": "Conscious Rap",
    "duration": "0:43:09",
    "favoriteSong": "Huntin' Wabbitz",
    "releaseDate": "Apr 5, 2024",
    "releaseDateISO": "2024-04-05"
  },
  {
    "rank": 115,
    "year": 2024,
    "artist": "The Story So Far",
    "album": "I Want To Disappear",
    "score": 69.7,
    "personalScore": 7.0,
    "trackCount": 10,
    "genre1": "Pop Punk",
    "genre2": "Emo Rock",
    "duration": "0:28:13",
    "favoriteSong": "Big Blind",
    "releaseDate": "Jun 21, 2024",
    "releaseDateISO": "2024-06-21"
  },
  {
    "rank": 116,
    "year": 2025,
    "artist": "Sabrina Carpenter",
    "album": "Man's Best Friend",
    "score": 69.3,
    "personalScore": 7.3,
    "trackCount": 12,
    "genre1": "Pop",
    "genre2": "",
    "duration": "0:38:24",
    "favoriteSong": "Manchild",
    "releaseDate": "Aug 29, 2026",
    "releaseDateISO": "2026-08-29"
  },
  {
    "rank": 117,
    "year": 2025,
    "artist": "Twenty One Pilots",
    "album": "Breach",
    "score": 69.0,
    "personalScore": 7.2,
    "trackCount": 13,
    "genre1": "Alt Pop",
    "genre2": "Electro-Rock",
    "duration": "0:47:28",
    "favoriteSong": "Downstairs",
    "releaseDate": "Sep 12, 2025",
    "releaseDateISO": "2025-09-12"
  },
  {
    "rank": 118,
    "year": 2022,
    "artist": "Tiny Moving Parts",
    "album": "Tiny Moving Parts",
    "score": 68.5,
    "personalScore": 7.1,
    "trackCount": 10,
    "genre1": "Math Rock",
    "genre2": "Emo",
    "duration": "0:27:31",
    "favoriteSong": "",
    "releaseDate": "Aug 26, 2022",
    "releaseDateISO": "2022-08-26"
  },
  {
    "rank": 119,
    "year": 2025,
    "artist": "Ben Quad",
    "album": "Wisher",
    "score": 68.4,
    "personalScore": 7.6,
    "trackCount": 10,
    "genre1": "Emo Revival",
    "genre2": "Midwest Emo",
    "duration": "0:30:48",
    "favoriteSong": "Classic Case of Guy on the Ground",
    "releaseDate": "Nov 14, 2025",
    "releaseDateISO": "2025-11-14"
  },
  {
    "rank": 120,
    "year": 2025,
    "artist": "Jesse Welles",
    "album": "Middle",
    "score": 68.2,
    "personalScore": 7.9,
    "trackCount": 12,
    "genre1": "Indie Folk",
    "genre2": "Rock",
    "duration": "0:43:58",
    "favoriteSong": "Why Don't You Love Me?",
    "releaseDate": "Feb 21, 2025",
    "releaseDateISO": "2025-02-21"
  },
  {
    "rank": 121,
    "year": 2025,
    "artist": "Blondshell",
    "album": "If You Asked For A Picture",
    "score": 68.1,
    "personalScore": 7.1,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Alt Pop",
    "duration": "0:46:49",
    "favoriteSong": "Two Times",
    "releaseDate": "May 2, 2025",
    "releaseDateISO": "2025-05-02"
  },
  {
    "rank": 122,
    "year": 2021,
    "artist": "Grayscale",
    "album": "Umbra",
    "score": 67.9,
    "personalScore": 7.1,
    "trackCount": 11,
    "genre1": "Pop Rock",
    "genre2": "Emo Pop",
    "duration": "0:36:24",
    "favoriteSong": "Carolina Skies",
    "releaseDate": "Aug 27, 2021",
    "releaseDateISO": "2021-08-27"
  },
  {
    "rank": 123,
    "year": 2021,
    "artist": "Lil Nas X",
    "album": "Montero",
    "score": 67.9,
    "personalScore": 6.7,
    "trackCount": 15,
    "genre1": "Pop",
    "genre2": "Hip-Hop",
    "duration": "0:41:17",
    "favoriteSong": "Don't Want It",
    "releaseDate": "Sep 17, 2021",
    "releaseDateISO": "2021-09-17"
  },
  {
    "rank": 125,
    "year": 2023,
    "artist": "Teenage Wrist",
    "album": "Still Love",
    "score": 67.1,
    "personalScore": 7.0,
    "trackCount": 12,
    "genre1": "Shoegaze",
    "genre2": "Grungegaze",
    "duration": "0:47:06",
    "favoriteSong": "Still Love",
    "releaseDate": "Aug 4, 2023",
    "releaseDateISO": "2023-08-04"
  },
  {
    "rank": 126,
    "year": 2025,
    "artist": "saturdays at your place",
    "album": "these things happen",
    "score": 67.0,
    "personalScore": 8.1,
    "trackCount": 10,
    "genre1": "Indie Emo",
    "genre2": "Bedroom Pop",
    "duration": "0:24:18",
    "favoriteSong": "what am i supposed to do",
    "releaseDate": "Sep 12, 2025",
    "releaseDateISO": "2025-09-12"
  },
  {
    "rank": 127,
    "year": 2020,
    "artist": "Machine Gun Kelly",
    "album": "Tickets To My Downfall",
    "score": 66.8,
    "personalScore": 5.5,
    "trackCount": 13,
    "genre1": "Pop Punk",
    "genre2": "Emo Rap",
    "duration": "0:36:09",
    "favoriteSong": "forget me too",
    "releaseDate": "Sep 25, 2020",
    "releaseDateISO": "2020-09-25"
  },
  {
    "rank": 128,
    "year": 2024,
    "artist": "Remi Wolf",
    "album": "Big Ideas",
    "score": 66.7,
    "personalScore": 7.3,
    "trackCount": 13,
    "genre1": "Pop Funk",
    "genre2": "Indie Pop",
    "duration": "0:43:10",
    "favoriteSong": "Alone in Miami",
    "releaseDate": "Jul 12, 2024",
    "releaseDateISO": "2024-07-12"
  },
  {
    "rank": 129,
    "year": 2021,
    "artist": "The Maine",
    "album": "XOXO: From Love & Anxiety In Real Time",
    "score": 66.5,
    "personalScore": 7.0,
    "trackCount": 10,
    "genre1": "Pop Rock",
    "genre2": "Alt Pop",
    "duration": "0:32:25",
    "favoriteSong": "Dirty, Pretty, Beautiful",
    "releaseDate": "Jul 9, 2021",
    "releaseDateISO": "2021-07-09"
  },
  {
    "rank": 130,
    "year": 2022,
    "artist": "Joyce Manor",
    "album": "40 oz to Fresno",
    "score": 66.4,
    "personalScore": 7.2,
    "trackCount": 9,
    "genre1": "Pop Punk",
    "genre2": "Indie Punk",
    "duration": "0:16:43",
    "favoriteSong": "",
    "releaseDate": "Jun 10, 2022",
    "releaseDateISO": "2022-06-10"
  },
  {
    "rank": 131,
    "year": 2021,
    "artist": "The Wold Is A Beautiful Place & I Am No Longer Afraid To Die",
    "album": "Illusory Walls",
    "score": 65.9,
    "personalScore": 8.1,
    "trackCount": 11,
    "genre1": "Post-Rock",
    "genre2": "Emo",
    "duration": "1:10:00",
    "favoriteSong": "Fewer Afraid",
    "releaseDate": "Oct 8, 2021",
    "releaseDateISO": "2021-10-08"
  },
  {
    "rank": 132,
    "year": 2024,
    "artist": "Sum 41",
    "album": "Heaven :x: Hell",
    "score": 65.8,
    "personalScore": 7.2,
    "trackCount": 20,
    "genre1": "Pop Punk",
    "genre2": "Metal",
    "duration": "0:55:12",
    "favoriteSong": "Dopamine",
    "releaseDate": "Mar 29, 2024",
    "releaseDateISO": "2024-03-29"
  },
  {
    "rank": 133,
    "year": 2022,
    "artist": "Alt-J",
    "album": "The Dream",
    "score": 65.7,
    "personalScore": 6.6,
    "trackCount": 12,
    "genre1": "Art Rock",
    "genre2": "Indie Pop",
    "duration": "0:49:27",
    "favoriteSong": "",
    "releaseDate": "Feb 11, 2022",
    "releaseDateISO": "2022-02-11"
  },
  {
    "rank": 134,
    "year": 2022,
    "artist": "Valleyheart",
    "album": "Heal My Head",
    "score": 65.1,
    "personalScore": 6.8,
    "trackCount": 12,
    "genre1": "Alt Rock",
    "genre2": "Post-Hardcore",
    "duration": "0:42:13",
    "favoriteSong": "",
    "releaseDate": "Jun 3, 2022",
    "releaseDateISO": "2022-06-03"
  },
  {
    "rank": 135,
    "year": 2024,
    "artist": "Oso Oso",
    "album": "life till bones",
    "score": 64.2,
    "personalScore": 8.0,
    "trackCount": 10,
    "genre1": "Indie Rock",
    "genre2": "Emo",
    "duration": "0:29:14",
    "favoriteSong": "all of my love",
    "releaseDate": "Aug 9, 2024",
    "releaseDateISO": "2024-08-09"
  },
  {
    "rank": 136,
    "year": 2025,
    "artist": "That Mexican OT",
    "album": "Recess",
    "score": 64.1,
    "personalScore": 7.0,
    "trackCount": 22,
    "genre1": "Southern Rap",
    "genre2": "Trap",
    "duration": "0:49:50",
    "favoriteSong": "Fuck On Me",
    "releaseDate": "Aug 14, 2025",
    "releaseDateISO": "2025-08-14"
  },
  {
    "rank": 137,
    "year": 2025,
    "artist": "Hot Mulligan",
    "album": "The Sound a Body Makes When It's Still",
    "score": 64.1,
    "personalScore": 7.4,
    "trackCount": 16,
    "genre1": "Emo",
    "genre2": "Post Pop Punk",
    "duration": "0:42:53",
    "favoriteSong": "Monica Lewinskibidi",
    "releaseDate": "Aug 22, 2026",
    "releaseDateISO": "2026-08-22"
  },
  {
    "rank": 138,
    "year": 2025,
    "artist": "Wet Leg",
    "album": "moisturizer",
    "score": 64.0,
    "personalScore": 6.7,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Post-Punk",
    "duration": "0:38:27",
    "favoriteSong": "catch these fists",
    "releaseDate": "Jul 11, 2025",
    "releaseDateISO": "2025-07-11"
  },
  {
    "rank": 139,
    "year": 2025,
    "artist": "Deep Sea Diver",
    "album": "Billboard Heart",
    "score": 63.5,
    "personalScore": 6.5,
    "trackCount": 11,
    "genre1": "Indie Pop",
    "genre2": "Dream Pop",
    "duration": "0:45:37",
    "favoriteSong": "Tiny Threads",
    "releaseDate": "Feb 28, 2025",
    "releaseDateISO": "2025-02-28"
  },
  {
    "rank": 140,
    "year": 2024,
    "artist": "Bayside",
    "album": "There Are Worse Things Than Being Alive",
    "score": 63.3,
    "personalScore": 6.2,
    "trackCount": 11,
    "genre1": "Pop Punk",
    "genre2": "Alternative Rock",
    "duration": "0:37:45",
    "favoriteSong": "Good Advice",
    "releaseDate": "Apr 5, 2024",
    "releaseDateISO": "2024-04-05"
  },
  {
    "rank": 141,
    "year": 2024,
    "artist": "The Dangerous Summer",
    "album": "Gravity",
    "score": 63.0,
    "personalScore": 6.3,
    "trackCount": 12,
    "genre1": "Alternative Rock",
    "genre2": "Emo",
    "duration": "0:46:26",
    "favoriteSong": "I Feel More Like Myself When I'm Losing It",
    "releaseDate": "Jun 21, 2024",
    "releaseDateISO": "2024-06-21"
  },
  {
    "rank": 142,
    "year": 2025,
    "artist": "Royel Otis",
    "album": "hickey",
    "score": 62.8,
    "personalScore": 7.6,
    "trackCount": 13,
    "genre1": "Dream Pop",
    "genre2": "Indie Rock",
    "duration": "0:38:25",
    "favoriteSong": "car",
    "releaseDate": "Aug 22, 2025",
    "releaseDateISO": "2025-08-22"
  },
  {
    "rank": 143,
    "year": 2024,
    "artist": "Maggie Rogers",
    "album": "Don't Forget Me",
    "score": 62.2,
    "personalScore": 6.5,
    "trackCount": 10,
    "genre1": "Indie Folk",
    "genre2": "Pop Rock",
    "duration": "0:35:53",
    "favoriteSong": "The Kill",
    "releaseDate": "Apr 12, 2024",
    "releaseDateISO": "2024-04-12"
  },
  {
    "rank": 144,
    "year": 2024,
    "artist": "Capstan",
    "album": "The Mosaic",
    "score": 61.8,
    "personalScore": 6.4,
    "trackCount": 18,
    "genre1": "Post-Hardcore",
    "genre2": "Metalcore",
    "duration": "1:03:00",
    "favoriteSong": "Heart To Heart",
    "releaseDate": "May 24, 2024",
    "releaseDateISO": "2024-05-24"
  },
  {
    "rank": 145,
    "year": 2024,
    "artist": "Tiny Moving Parts",
    "album": "Deep in the Blue",
    "score": 61.8,
    "personalScore": 6.7,
    "trackCount": 10,
    "genre1": "Emo",
    "genre2": "Math Rock",
    "duration": "0:25:49",
    "favoriteSong": "Before I Go",
    "releaseDate": "Nov 15, 2024",
    "releaseDateISO": "2024-11-15"
  },
  {
    "rank": 146,
    "year": 2024,
    "artist": "Belmont",
    "album": "Liminal",
    "score": 61.7,
    "personalScore": 6.1,
    "trackCount": 12,
    "genre1": "Pop Punk",
    "genre2": "Easycore",
    "duration": "0:39:00",
    "favoriteSong": "SSX Trickmont",
    "releaseDate": "Apr 12, 2024",
    "releaseDateISO": "2024-04-12"
  },
  {
    "rank": 147,
    "year": 2021,
    "artist": "Chunk! No, Captain Chunk!",
    "album": "Gone Are The Good Days",
    "score": 61.4,
    "personalScore": 6.1,
    "trackCount": 12,
    "genre1": "Pop Punk",
    "genre2": "Easycore",
    "duration": "0:44:27",
    "favoriteSong": "Complete You",
    "releaseDate": "Jul 30, 2021",
    "releaseDateISO": "2021-07-30"
  },
  {
    "rank": 148,
    "year": 2025,
    "artist": "The Wonder Years",
    "album": "Burst & Decay (Volume III)",
    "score": 61.2,
    "personalScore": 6.6,
    "trackCount": 9,
    "genre1": "Emo",
    "genre2": "Acoustic",
    "duration": "0:30:48",
    "favoriteSong": "Junebug",
    "releaseDate": "May 9, 2025",
    "releaseDateISO": "2025-05-09"
  },
  {
    "rank": 149,
    "year": 2025,
    "artist": "La Dispute",
    "album": "No One Was Driving the Car",
    "score": 61.1,
    "personalScore": 6.2,
    "trackCount": 14,
    "genre1": "Post-Hardcore",
    "genre2": "Spoken Word Emo",
    "duration": "1:04:00",
    "favoriteSong": "Environmental Catastrophe Film",
    "releaseDate": "Sep 5, 2025",
    "releaseDateISO": "2025-09-05"
  },
  {
    "rank": 150,
    "year": 2020,
    "artist": "The 1975",
    "album": "Notes On A Conditional Form",
    "score": 61.0,
    "personalScore": 7.0,
    "trackCount": 22,
    "genre1": "Indie Pop",
    "genre2": "Experimental",
    "duration": "1:20:00",
    "favoriteSong": "Jesus Christ 2005 God Bless America",
    "releaseDate": "May 22, 2020",
    "releaseDateISO": "2020-05-22"
  },
  {
    "rank": 151,
    "year": 2021,
    "artist": "Cavetown",
    "album": "Man's Best Friend",
    "score": 60.9,
    "personalScore": 5.5,
    "trackCount": 7,
    "genre1": "Bedroom Pop",
    "genre2": "Indie Folk",
    "duration": "0:24:49",
    "favoriteSong": "Paul",
    "releaseDate": "Jun 4, 2021",
    "releaseDateISO": "2021-06-04"
  },
  {
    "rank": 152,
    "year": 2025,
    "artist": "Tyler, The Creator",
    "album": "Don't Tap The Glass",
    "score": 60.8,
    "personalScore": 6.3,
    "trackCount": 10,
    "genre1": "Hip-Hop",
    "genre2": "Neo-Soul",
    "duration": "0:28:30",
    "favoriteSong": "Don't Tap That Glass / Tweakin'",
    "releaseDate": "Jul 21, 2025",
    "releaseDateISO": "2025-07-21"
  },
  {
    "rank": 153,
    "year": 2023,
    "artist": "Home Is Where",
    "album": "the whaler",
    "score": 60.5,
    "personalScore": 6.6,
    "trackCount": 10,
    "genre1": "Post-Hardcore",
    "genre2": "Art Punk",
    "duration": "0:34:59",
    "favoriteSong": "Skin Meadow",
    "releaseDate": "Jun 16, 2023",
    "releaseDateISO": "2023-06-16"
  },
  {
    "rank": 154,
    "year": 2021,
    "artist": "Dinosar Jr.",
    "album": "Sweep It Into Space",
    "score": 60.4,
    "personalScore": 6.3,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Alternative",
    "duration": "0:44:57",
    "favoriteSong": "I Ran Away",
    "releaseDate": "Apr 23, 2021",
    "releaseDateISO": "2021-04-23"
  },
  {
    "rank": 155,
    "year": 2023,
    "artist": "Citizen",
    "album": "Calling The Dogs",
    "score": 59.6,
    "personalScore": 6.9,
    "trackCount": 11,
    "genre1": "Indie Rock",
    "genre2": "Post-Punk",
    "duration": "0:33:45",
    "favoriteSong": "If You're Lonely",
    "releaseDate": "Oct 6, 2023",
    "releaseDateISO": "2023-10-06"
  },
  {
    "rank": 156,
    "year": 2022,
    "artist": "Whitney",
    "album": "SPARK",
    "score": 58.8,
    "personalScore": 6.3,
    "trackCount": 12,
    "genre1": "Indie Pop",
    "genre2": "Soft Rock",
    "duration": "0:38:18",
    "favoriteSong": "",
    "releaseDate": "Sep 16, 2022",
    "releaseDateISO": "2022-09-16"
  },
  {
    "rank": 157,
    "year": 2025,
    "artist": "Car Seat Headrest",
    "album": "The Scholars",
    "score": 58.4,
    "personalScore": 6.4,
    "trackCount": 9,
    "genre1": "Indie Rock",
    "genre2": "Lo-Fi",
    "duration": "1:10:00",
    "favoriteSong": "CCF",
    "releaseDate": "May 2, 2025",
    "releaseDateISO": "2025-05-02"
  },
  {
    "rank": 158,
    "year": 2024,
    "artist": "Everything Everything",
    "album": "Mountain Head",
    "score": 58.3,
    "personalScore": 5.4,
    "trackCount": 14,
    "genre1": "Experimental Pop",
    "genre2": "Alt Rock",
    "duration": "0:54:53",
    "favoriteSong": "Cold Reactor",
    "releaseDate": "Mar 1, 2024",
    "releaseDateISO": "2024-03-01"
  },
  {
    "rank": 159,
    "year": 2025,
    "artist": "Arm's Length",
    "album": "There's A Whole World Out There",
    "score": 58.1,
    "personalScore": 6.8,
    "trackCount": 12,
    "genre1": "Emo",
    "genre2": "Post-Hardcore",
    "duration": "0:46:32",
    "favoriteSong": "The Wound",
    "releaseDate": "May 16, 2025",
    "releaseDateISO": "2025-05-16"
  },
  {
    "rank": 160,
    "year": 2025,
    "artist": "Slow Joy",
    "album": "A Joy So Slow At Times I Don't Think It's Coming",
    "score": 57.0,
    "personalScore": 7.5,
    "trackCount": 13,
    "genre1": "Shoegaze",
    "genre2": "Emo",
    "duration": "0:31:45",
    "favoriteSong": "Gruesome",
    "releaseDate": "May 16, 2025",
    "releaseDateISO": "2025-05-16"
  },
  {
    "rank": 161,
    "year": 2020,
    "artist": "Taylor Swift",
    "album": "Folklore",
    "score": 56.8,
    "personalScore": 6.4,
    "trackCount": 16,
    "genre1": "Indie Folk",
    "genre2": "Chamber Pop",
    "duration": "1:03:00",
    "favoriteSong": "Betty",
    "releaseDate": "Jul 24, 2020",
    "releaseDateISO": "2020-07-24"
  },
  {
    "rank": 162,
    "year": 2024,
    "artist": "Vampire Weekend",
    "album": "Only God Was Above Us",
    "score": 56.4,
    "personalScore": 5.9,
    "trackCount": 10,
    "genre1": "Indie Rock",
    "genre2": "Art Pop",
    "duration": "0:47:14",
    "favoriteSong": "Prep-School Gangsters",
    "releaseDate": "Apr 5, 2024",
    "releaseDateISO": "2024-04-05"
  },
  {
    "rank": 163,
    "year": 2021,
    "artist": "Run River North",
    "album": "Creatures In Your Head",
    "score": 56.2,
    "personalScore": 5.7,
    "trackCount": 10,
    "genre1": "Indie Folk",
    "genre2": "Alternative",
    "duration": "0:33:55",
    "favoriteSong": "Spiders",
    "releaseDate": "Feb 12, 2021",
    "releaseDateISO": "2021-02-12"
  },
  {
    "rank": 164,
    "year": 2021,
    "artist": "Brockhampton",
    "album": "ROADRUNNER: NEW LIGHT, NEW MACINE",
    "score": 56.0,
    "personalScore": 5.4,
    "trackCount": 13,
    "genre1": "Hip-Hop",
    "genre2": "Experimental Rap",
    "duration": "0:46:38",
    "favoriteSong": "THE LIGHT PT. II",
    "releaseDate": "Apr 9, 2021",
    "releaseDateISO": "2021-04-09"
  },
  {
    "rank": 165,
    "year": 2022,
    "artist": "All Get Out",
    "album": "Kodak",
    "score": 55.6,
    "personalScore": 6.1,
    "trackCount": 10,
    "genre1": "Indie Rock",
    "genre2": "Emo",
    "duration": "0:43:14",
    "favoriteSong": "",
    "releaseDate": "Jun 3, 2022",
    "releaseDateISO": "2022-06-03"
  },
  {
    "rank": 167,
    "year": 2025,
    "artist": "Michael Cera Palin",
    "album": "We Could Be Brave",
    "score": 55.0,
    "personalScore": 5.7,
    "trackCount": 10,
    "genre1": "Emo",
    "genre2": "Math Rock",
    "duration": "0:47:13",
    "favoriteSong": "Murder Hornet Fursona",
    "releaseDate": "Mar 7, 2025",
    "releaseDateISO": "2025-03-07"
  },
  {
    "rank": 168,
    "year": 2020,
    "artist": "Glass Animals",
    "album": "Dreamland",
    "score": 54.6,
    "personalScore": 5.3,
    "trackCount": 14,
    "genre1": "Psychedelic Pop",
    "genre2": "Synthpop",
    "duration": "0:45:24",
    "favoriteSong": "Hot Sugar",
    "releaseDate": "Aug 7, 2020",
    "releaseDateISO": "2020-08-07"
  },
  {
    "rank": 169,
    "year": 2025,
    "artist": "Have Mercy",
    "album": "the loneliest place i've ever been",
    "score": 53.7,
    "personalScore": 6.9,
    "trackCount": 10,
    "genre1": "Emo Rock",
    "genre2": "",
    "duration": "0:34:36",
    "favoriteSong": "medicine",
    "releaseDate": "Aug 29, 2025",
    "releaseDateISO": "2025-08-29"
  },
  {
    "rank": 170,
    "year": 2024,
    "artist": "Real Friends",
    "album": "Blue Hour",
    "score": 53.7,
    "personalScore": 5.8,
    "trackCount": 13,
    "genre1": "Pop Punk",
    "genre2": "Emo",
    "duration": "0:37:24",
    "favoriteSong": "Waiting Room",
    "releaseDate": "Oct 11, 2024",
    "releaseDateISO": "2024-10-11"
  },
  {
    "rank": 171,
    "year": 2024,
    "artist": "Tyler, The Creator",
    "album": "CHROMAKOPIA",
    "score": 53.6,
    "personalScore": 6.0,
    "trackCount": 14,
    "genre1": "Hip-Hop",
    "genre2": "Experimental Rap",
    "duration": "0:53:00",
    "favoriteSong": "Thought I Was Dead",
    "releaseDate": "Oct 28, 2024",
    "releaseDateISO": "2024-10-28"
  },
  {
    "rank": 172,
    "year": 2021,
    "artist": "68",
    "album": "Give One Take One",
    "score": 53.0,
    "personalScore": 5.0,
    "trackCount": 10,
    "genre1": "Noise Rock",
    "genre2": "Post-Hardcore",
    "duration": "0:40:20",
    "favoriteSong": "Nervous Passenger",
    "releaseDate": "Mar 26, 2021",
    "releaseDateISO": "2021-03-26"
  },
  {
    "rank": 174,
    "year": 2025,
    "artist": "Pool Kids",
    "album": "Easier Said Than Done",
    "score": 52.3,
    "personalScore": 5.8,
    "trackCount": 11,
    "genre1": "Math Rock",
    "genre2": "Emo",
    "duration": "0:39:49",
    "favoriteSong": "Sorry Not Sorry",
    "releaseDate": "Aug 15, 2025",
    "releaseDateISO": "2025-08-15"
  },
  {
    "rank": 175,
    "year": 2024,
    "artist": "Say Anything",
    "album": "...Is Committed",
    "score": 51.7,
    "personalScore": 5.1,
    "trackCount": 12,
    "genre1": "Emo Rock",
    "genre2": "Indie Pop",
    "duration": "1:00:00",
    "favoriteSong": "ON CUM",
    "releaseDate": "May 24, 2024",
    "releaseDateISO": "2024-05-24"
  },
  {
    "rank": 176,
    "year": 2023,
    "artist": "68",
    "album": "Yes, and...",
    "score": 51.5,
    "personalScore": 6.5,
    "trackCount": 9,
    "genre1": "Noise Rock",
    "genre2": "Mathcore",
    "duration": "0:32:42",
    "favoriteSong": "The Catpains Sat",
    "releaseDate": "Sep 29, 2023",
    "releaseDateISO": "2023-09-29"
  },
  {
    "rank": 177,
    "year": 2025,
    "artist": "Laura Stevenson",
    "album": "Late Great",
    "score": 51.5,
    "personalScore": 5.9,
    "trackCount": 12,
    "genre1": "Indie Folk",
    "genre2": "",
    "duration": "0:38:43",
    "favoriteSong": "#1",
    "releaseDate": "Jun 27, 2025",
    "releaseDateISO": "2025-06-27"
  },
  {
    "rank": 179,
    "year": 2025,
    "artist": "The Dirty Nil",
    "album": "The Lash",
    "score": 51.1,
    "personalScore": 6.1,
    "trackCount": 10,
    "genre1": "Punk Rock",
    "genre2": "Garage Rock",
    "duration": "0:29:50",
    "favoriteSong": "Rock N' Roll Band",
    "releaseDate": "Jul 25, 2025",
    "releaseDateISO": "2025-07-25"
  },
  {
    "rank": 180,
    "year": 2024,
    "artist": "Neck Deep",
    "album": "Neck Deep",
    "score": 51.1,
    "personalScore": 5.2,
    "trackCount": 10,
    "genre1": "Pop Punk",
    "genre2": "Alternative Rock",
    "duration": "0:33:18",
    "favoriteSong": "Heartbreak Of The Century",
    "releaseDate": "Jan 19, 2024",
    "releaseDateISO": "2024-01-19"
  },
  {
    "rank": 181,
    "year": 2026,
    "artist": "Zach Bryan",
    "album": "With Heaven On Top",
    "score": 50.8,
    "personalScore": 6.0,
    "trackCount": 25,
    "genre1": "Country",
    "genre2": "Americana",
    "duration": "1:18:00",
    "favoriteSong": "Bad News",
    "releaseDate": "Jan 9, 2026",
    "releaseDateISO": "2026-01-09"
  },
  {
    "rank": 182,
    "year": 2025,
    "artist": "Sleep Token",
    "album": "Even In Arcadia",
    "score": 50.7,
    "personalScore": 5.3,
    "trackCount": 10,
    "genre1": "Alt Metal",
    "genre2": "Art Rock",
    "duration": "0:56:34",
    "favoriteSong": "Gethsemane",
    "releaseDate": "May 9, 2025",
    "releaseDateISO": "2025-05-09"
  },
  {
    "rank": 183,
    "year": 2025,
    "artist": "Fickle Friends",
    "album": "Fickle Friends",
    "score": 50.4,
    "personalScore": 5.6,
    "trackCount": 11,
    "genre1": "Indie Pop",
    "genre2": "Synthpop",
    "duration": "0:31:59",
    "favoriteSong": "WOW",
    "releaseDate": "Nov 7, 2025",
    "releaseDateISO": "2025-11-07"
  },
  {
    "rank": 185,
    "year": 2021,
    "artist": "Free Throw",
    "album": "Piecing It Together",
    "score": 49.5,
    "personalScore": 5.9,
    "trackCount": 12,
    "genre1": "Emo",
    "genre2": "Indie Rock",
    "duration": "0:39:18",
    "favoriteSong": "Ocular Pat Down",
    "releaseDate": "Jun 25, 2021",
    "releaseDateISO": "2021-06-25"
  },
  {
    "rank": 186,
    "year": 2023,
    "artist": "Just Friends",
    "album": "Gusher",
    "score": 49.2,
    "personalScore": 5.5,
    "trackCount": 13,
    "genre1": "Funk Rock",
    "genre2": "Emo Pop",
    "duration": "0:43:13",
    "favoriteSong": "Zaza in the Sun:-)",
    "releaseDate": "Sep 1, 2023",
    "releaseDateISO": "2023-09-01"
  },
  {
    "rank": 187,
    "year": 2024,
    "artist": "Ben Quad",
    "album": "Ephemera",
    "score": 48.9,
    "personalScore": 5.5,
    "trackCount": 5,
    "genre1": "Emo",
    "genre2": "Post-Hardcore",
    "duration": "0:11:04",
    "favoriteSong": "You'll Get Nothing and Like It",
    "releaseDate": "Oct 25, 2024",
    "releaseDateISO": "2024-10-25"
  },
  {
    "rank": 188,
    "year": 2024,
    "artist": "Matt Kerekes",
    "album": "To Dream of Something Wicked",
    "score": 48.7,
    "personalScore": 5.7,
    "trackCount": 12,
    "genre1": "Indie Rock",
    "genre2": "Alt Folk",
    "duration": "0:41:32",
    "favoriteSong": "My Lonely Ghost",
    "releaseDate": "Oct 18, 2024",
    "releaseDateISO": "2024-10-18"
  },
  {
    "rank": 189,
    "year": 2024,
    "artist": "Childish Gambino",
    "album": "Bando Stone and The New World",
    "score": 48.6,
    "personalScore": 4.6,
    "trackCount": 13,
    "genre1": "R&B",
    "genre2": "Hip-Hop",
    "duration": "1:00:00",
    "favoriteSong": "Lithonia",
    "releaseDate": "Jul 19, 2024",
    "releaseDateISO": "2024-07-19"
  },
  {
    "rank": 190,
    "year": 2026,
    "artist": "A$AP Rocky",
    "album": "Don't Be Dumb",
    "score": 48.1,
    "personalScore": 5.5,
    "trackCount": 17,
    "genre1": "Hip Hop",
    "genre2": "Trap",
    "duration": "0:59:00",
    "favoriteSong": "",
    "releaseDate": "Jan 16, 2026",
    "releaseDateISO": "2026-01-16"
  },
  {
    "rank": 191,
    "year": 2025,
    "artist": "Anchor & Braille",
    "album": "New Mexico",
    "score": 47.1,
    "personalScore": 4.8,
    "trackCount": 14,
    "genre1": "Indie Pop",
    "genre2": "Alt Rock",
    "duration": "0:43:50",
    "favoriteSong": "Rattlesnake",
    "releaseDate": "Jul 25, 2025",
    "releaseDateISO": "2025-07-25"
  },
  {
    "rank": 193,
    "year": 2025,
    "artist": "Deafhaven",
    "album": "Lonely People with Power",
    "score": 46.9,
    "personalScore": 5.4,
    "trackCount": 12,
    "genre1": "Blackgaze",
    "genre2": "Post-Metal",
    "duration": "1:02:00",
    "favoriteSong": "Doberman",
    "releaseDate": "Mar 28, 2025",
    "releaseDateISO": "2025-03-28"
  },
  {
    "rank": 194,
    "year": 2024,
    "artist": "Four Year Strong",
    "album": "analysis paralysis",
    "score": 44.3,
    "personalScore": 5.0,
    "trackCount": 12,
    "genre1": "Post-Hardcore",
    "genre2": "Pop Punk",
    "duration": "0:35:29",
    "favoriteSong": "dead end friend",
    "releaseDate": "Aug 9, 2024",
    "releaseDateISO": "2024-08-09"
  },
  {
    "rank": 195,
    "year": 2024,
    "artist": "Anthony Raneiri",
    "album": "Everyday Royalty",
    "score": 44.2,
    "personalScore": 5.6,
    "trackCount": 7,
    "genre1": "Pop Rock",
    "genre2": "Alternative",
    "duration": "0:23:16",
    "favoriteSong": "I'll Be Fine",
    "releaseDate": "Nov 15, 2024",
    "releaseDateISO": "2024-11-15"
  },
  {
    "rank": 196,
    "year": 2025,
    "artist": "Lucy Dacus",
    "album": "Forever Is A Feeling",
    "score": 43.6,
    "personalScore": 5.5,
    "trackCount": 13,
    "genre1": "Indie Singer-Songwriter",
    "genre2": "",
    "duration": "0:43:38",
    "favoriteSong": "Most Wanted Man",
    "releaseDate": "Mar 28, 2025",
    "releaseDateISO": "2025-03-28"
  },
  {
    "rank": 197,
    "year": 2025,
    "artist": "Deadguy",
    "album": "Near-Death Travel Services",
    "score": 43.5,
    "personalScore": 6.0,
    "trackCount": 11,
    "genre1": "Hardcore Punk",
    "genre2": "Metalcore",
    "duration": "0:36:25",
    "favoriteSong": "New Best Friend",
    "releaseDate": "Jun 7, 2025",
    "releaseDateISO": "2025-06-07"
  },
  {
    "rank": 198,
    "year": 2024,
    "artist": "Zach Bryan",
    "album": "The Great American Bar Scene",
    "score": 43.3,
    "personalScore": 5.3,
    "trackCount": 19,
    "genre1": "Americana",
    "genre2": "Country",
    "duration": "1:03:00",
    "favoriteSong": "The Great American Bar Scene",
    "releaseDate": "Jul 4, 2024",
    "releaseDateISO": "2024-07-04"
  },
  {
    "rank": 199,
    "year": 2025,
    "artist": "Action/Adventure",
    "album": "Ever After",
    "score": 43.0,
    "personalScore": 5.1,
    "trackCount": 13,
    "genre1": "Pop Punk",
    "genre2": "Easycore",
    "duration": "0:39:57",
    "favoriteSong": "Big Al Dente",
    "releaseDate": "Oct 24, 2025",
    "releaseDateISO": "2025-10-24"
  },
  {
    "rank": 200,
    "year": 2025,
    "artist": "Whitney",
    "album": "Small Talk",
    "score": 43.0,
    "personalScore": 4.6,
    "trackCount": 11,
    "genre1": "Indie Soul",
    "genre2": "Folk Pop",
    "duration": "0:36:00",
    "favoriteSong": "Evangeline",
    "releaseDate": "Nov 7, 2025",
    "releaseDateISO": "2025-11-07"
  },
  {
    "rank": 201,
    "year": 2022,
    "artist": "Typhoon",
    "album": "Underground Complex No. 1",
    "score": 43.0,
    "personalScore": 5.4,
    "trackCount": 8,
    "genre1": "Indie Folk",
    "genre2": "Chamber Pop",
    "duration": "0:23:48",
    "favoriteSong": "",
    "releaseDate": "Apr 15, 2022",
    "releaseDateISO": "2022-04-15"
  },
  {
    "rank": 202,
    "year": 2024,
    "artist": "Billie Eilish",
    "album": "HIT ME HARD AND SOFT",
    "score": 42.7,
    "personalScore": 4.8,
    "trackCount": 10,
    "genre1": "Alt Pop",
    "genre2": "Synthpop",
    "duration": "0:43:50",
    "favoriteSong": "BIRDS OF A FEATHER",
    "releaseDate": "May 17, 2024",
    "releaseDateISO": "2024-05-17"
  },
  {
    "rank": 203,
    "year": 2024,
    "artist": "From Indian Lakes",
    "album": "Head Void",
    "score": 42.5,
    "personalScore": 4.9,
    "trackCount": 10,
    "genre1": "Indie Rock",
    "genre2": "Dream Pop",
    "duration": "0:32:31",
    "favoriteSong": "The Lines",
    "releaseDate": "May 15, 2024",
    "releaseDateISO": "2024-05-15"
  },
  {
    "rank": 204,
    "year": 2025,
    "artist": "Heart Attack Man",
    "album": "Joyride The Pale Horse",
    "score": 40.9,
    "personalScore": 5.2,
    "trackCount": 12,
    "genre1": "Punk Rock",
    "genre2": "Emo",
    "duration": "0:29:35",
    "favoriteSong": "Joyride The Pale Horse",
    "releaseDate": "Apr 25, 2025",
    "releaseDateISO": "2025-04-25"
  },
  {
    "rank": 205,
    "year": 2024,
    "artist": "Beabadoobee",
    "album": "This Is How Tomorrow Moves",
    "score": 40.0,
    "personalScore": 4.7,
    "trackCount": 14,
    "genre1": "Indie Rock",
    "genre2": "Britpop",
    "duration": "0:41:28",
    "favoriteSong": "Take A Bite",
    "releaseDate": "Sep 9, 2024",
    "releaseDateISO": "2024-09-09"
  },
  {
    "rank": 206,
    "year": 2025,
    "artist": "Hundredth",
    "album": "Faded Splendor",
    "score": 37.9,
    "personalScore": 4.9,
    "trackCount": 10,
    "genre1": "Shoegaze",
    "genre2": "Dreamgaze",
    "duration": "0:34:00",
    "favoriteSong": "Curve",
    "releaseDate": "May 26, 2025",
    "releaseDateISO": "2025-05-26"
  },
  {
    "rank": 207,
    "year": 2025,
    "artist": "Charlie Crockett",
    "album": "Dollar A Day",
    "score": 37.9,
    "personalScore": 4.7,
    "trackCount": 15,
    "genre1": "Country",
    "genre2": "Americana",
    "duration": "0:46:53",
    "favoriteSong": "Ain't That Right",
    "releaseDate": "Aug 8, 2025",
    "releaseDateISO": "2025-08-08"
  },
  {
    "rank": 208,
    "year": 2025,
    "artist": "The Beaches",
    "album": "No Hard Feelings",
    "score": 37.7,
    "personalScore": 5.0,
    "trackCount": 11,
    "genre1": "Indie Rock",
    "genre2": "Pop Rock",
    "duration": "0:34:11",
    "favoriteSong": "Did I Say Too Much",
    "releaseDate": "Aug 29, 2025",
    "releaseDateISO": "2025-08-29"
  },
  {
    "rank": 209,
    "year": 2025,
    "artist": "Dance Gavin Dance",
    "album": "Pantheon",
    "score": 37.3,
    "personalScore": 4.3,
    "trackCount": 13,
    "genre1": "Post-Hardcore",
    "genre2": "Prog Rock",
    "duration": "0:55:13",
    "favoriteSong": "Midnight at McGuffy's",
    "releaseDate": "Sep 12, 2025",
    "releaseDateISO": "2025-09-12"
  },
  {
    "rank": 210,
    "year": 2024,
    "artist": "Vince Staples",
    "album": "Dark Times",
    "score": 36.1,
    "personalScore": 4.5,
    "trackCount": 13,
    "genre1": "Hip-Hop",
    "genre2": "Alternative",
    "duration": "0:35:05",
    "favoriteSong": "Etouffee",
    "releaseDate": "May 24, 2024",
    "releaseDateISO": "2024-05-24"
  },
  {
    "rank": 211,
    "year": 2024,
    "artist": "Twenty One Pilots",
    "album": "Clancy",
    "score": 35.5,
    "personalScore": 4.0,
    "trackCount": 13,
    "genre1": "Alternative Pop",
    "genre2": "Electropop",
    "duration": "0:47:18",
    "favoriteSong": "Next Semester",
    "releaseDate": "May 24, 2024",
    "releaseDateISO": "2024-05-24"
  },
  {
    "rank": 212,
    "year": 2025,
    "artist": "The World Is a Beautiful Place & I Am No Longer Afraid To Die",
    "album": "Dreams of Being Dust",
    "score": 35.4,
    "personalScore": 4.5,
    "trackCount": 11,
    "genre1": "Emo",
    "genre2": "Post-Rock",
    "duration": "0:44:24",
    "favoriteSong": "Captagon",
    "releaseDate": "Aug 22, 2025",
    "releaseDateISO": "2025-08-22"
  },
  {
    "rank": 213,
    "year": 2024,
    "artist": "Linkin Park",
    "album": "From Zero",
    "score": 34.9,
    "personalScore": 4.3,
    "trackCount": 10,
    "genre1": "Alternative Metal",
    "genre2": "Nu-Metal",
    "duration": "0:41:46",
    "favoriteSong": "IGYEIH",
    "releaseDate": "May 16, 2024",
    "releaseDateISO": "2024-05-16"
  },
  {
    "rank": 214,
    "year": 2025,
    "artist": "Deftones",
    "album": "private music",
    "score": 34.7,
    "personalScore": 4.4,
    "trackCount": 11,
    "genre1": "Alt Metal",
    "genre2": "Shoegaze",
    "duration": "0:42:29",
    "favoriteSong": "my mind is a mountain",
    "releaseDate": "Aug 22, 2025",
    "releaseDateISO": "2025-08-22"
  },
  {
    "rank": 217,
    "year": 2025,
    "artist": "flipturn",
    "album": "Burnout Days",
    "score": 33.0,
    "personalScore": 4.2,
    "trackCount": 12,
    "genre1": "Indie Pop",
    "genre2": "Alt Rock",
    "duration": "0:43:30",
    "favoriteSong": "Swim Between Trees",
    "releaseDate": "Jan 24, 2025",
    "releaseDateISO": "2025-01-24"
  },
  {
    "rank": 218,
    "year": 2024,
    "artist": "Many Eyes",
    "album": "The Light Age",
    "score": 31.7,
    "personalScore": 4.4,
    "trackCount": 10,
    "genre1": "Metalcore",
    "genre2": "Prog Metal",
    "duration": "0:35:17",
    "favoriteSong": "Revelation",
    "releaseDate": "Sep 6, 2024",
    "releaseDateISO": "2024-09-06"
  },
  {
    "rank": 219,
    "year": 2024,
    "artist": "Delta Sleep",
    "album": "Blue Garden",
    "score": 29.8,
    "personalScore": 4.2,
    "trackCount": 12,
    "genre1": "Math Rock",
    "genre2": "Post-Rock",
    "duration": "0:42:53",
    "favoriteSong": "Glow",
    "releaseDate": "Oct 11, 2024",
    "releaseDateISO": "2024-10-11"
  },
  {
    "rank": 221,
    "year": 2024,
    "artist": "State Champs",
    "album": "State Champs",
    "score": 26.1,
    "personalScore": 4.1,
    "trackCount": 12,
    "genre1": "Pop Punk",
    "genre2": "Easycore",
    "duration": "0:36:54",
    "favoriteSong": "Light Blue",
    "releaseDate": "Nov 8, 2024",
    "releaseDateISO": "2024-11-08"
  },
  {
    "rank": 222,
    "year": 2024,
    "artist": "Better Lovers",
    "album": "Highly Irresponsible",
    "score": 24.3,
    "personalScore": 3.7,
    "trackCount": 10,
    "genre1": "Metalcore",
    "genre2": "Post-Hardcore",
    "duration": "0:35:02",
    "favoriteSong": "Future Myopia",
    "releaseDate": "Oct 25, 2024",
    "releaseDateISO": "2024-10-25"
  },
  {
    "rank": 223,
    "year": 2024,
    "artist": "Marianas Trench",
    "album": "Haven",
    "score": 21.1,
    "personalScore": 3.0,
    "trackCount": 13,
    "genre1": "Pop Rock",
    "genre2": "Symphonic Pop",
    "duration": "0:52:48",
    "favoriteSong": "I'm Not Getting Better",
    "releaseDate": "Oct 30, 2024",
    "releaseDateISO": "2024-10-30"
  }
];
